require: rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/*'
    - 'spec/**/*'
    - 'config/**/*'

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'
    - 'app/admin/*'
