version: '3'
services:
  postgres:
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    container_name: simirise
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PASSWORD=password
    depends_on:
      - "postgres"
    links:
      - postgres
    restart: always
    volumes:
      - .:/simirise
networks:
  default:
    external:
      name: local
volumes:
  postgres:
